### ISSUE TITLE
[Request] Add wemod

### ISSUE THREAD

**Issue by IsaacWangTT** [Ryanjiena/Meta#315]
### Package Name

wemod

### Latest version

8.0.4

### Description

为您最喜欢的游戏提供上千款免费修改器 - 全部都集成在一个地方。

### Homepage

https://www.wemod.com/

### License

Unknown

### Graphical interface

Yes

### Portable version

No

### Some indication of popularity/repute

WeMod让修改器作者与超过1500万玩家分享他们的修改器。 

### Download link(s)

```powershell
https://www.wemod.com/download/direct
```

**Comment by Ryanjiena** [comment]
`https://www.wemod.com/download/direct` 这个链接下载的程序是在线安装器吧

**Comment by Ryanjiena** [comment]
看了一下，没有找到这个应用的离线安装包。

**Comment by IsaacWangTT** [comment]
> ~看了一下，没有找到这个应用的离线安装包~ 已找到，今晚修改

好的好的十分感谢

**Comment by JaimeZeng** [comment]
https://github.com/Ryanjiena/Meta/blob/master/bucket/wxmod.json

https://github.com/Ryanjiena/Meta/blob/master/bucket/wxmod-beta.json

**Comment by IsaacWangTT** [comment]
> https://github.com/Ryanjiena/Meta/blob/master/bucket/wxmod.json
> 
> https://github.com/Ryanjiena/Meta/blob/master/bucket/wxmod-beta.json

冒昧的问下，为什么是wxmod😂

**Comment by JaimeZeng** [comment]
这也太尴尬了吧......哈哈🤣

**Comment by Ryanjiena** [comment]
这下好了，刚刚修改了。

**Comment by Ryanjiena** [comment]
https://github.com/Ryanjiena/Meta/blob/master/bucket/wemod.json

https://github.com/Ryanjiena/Meta/blob/master/bucket/wemod-beta.json
