### ISSUE TITLE
RunningCheese 的更新检测不是最新

### ISSUE THREAD

**Issue by wordpure** [Ryanjiena/Meta#347]
感觉现在的更新是通过第三方站点来检测的，速度比较慢，建议从官方发布文章的标题中提取。

- [RunningCheese Firefox](https://www.runningcheese.com/firefox)
- [RunningCheese Chrome](https://www.runningcheese.com/chrome)
- [RunningCheese Edge](https://www.runningcheese.com/edge)

![图片](https://user-images.githubusercontent.com/68013962/167281162-466ba472-7cdd-4fb7-936c-2dc171c94d75.png)

![图片](https://user-images.githubusercontent.com/68013962/167281193-dea4a53d-5abc-4113-9c49-fe83dd4945be.png)

**Comment by Ryanjiena** [comment]
那个是从我 onedrive 里更新的，因为 oneindex 使用的 cf worrkers 一天有请求数量限制，所以我全部下载到这个 https://github.com/Ryanjiena/MetaVersion 里了

**Comment by Ryanjiena** [comment]
这种第三方软件的检测更新全部移动到 https://github.com/Ryanjiena/MetaVersion 仓库了，有问题的话去那个仓库下讨论吧

**Comment by Ryanjiena** [comment]
> 建议从官方发布文章的标题中提取。

检测更新很简单，但是有新版本号但是文件还是旧的，他网站没有提供下载直链，还需要我这边下载上传到 onedrive

**Comment by Ryanjiena** [comment]
我 vps 到期了，等下个月买到新服务器我再解决这些软件的自动下载同步更新的问题。

**Comment by Ryanjiena** [comment]
浏览器的可以暂时用仓库下的带 plus 的包

**Comment by wordpure** [comment]
了解了，感谢。

**Comment by Ryanjiena** [comment]
在的话你帮我问一下他蓝奏云盘里的压缩包名上能不能加一个版本号😂我本地这边处理起来有点麻烦(>﹏<)

**Comment by wordpure** [comment]
> 你在奶酪的那个群里吗（微信群或者QQ群）？

我只关注了奶酪的公众号😂

他在 Github 有个 [RunningCheese-Firefox](https://github.com/runningcheese/RunningCheese-Firefox/issues)   的仓库，或许可以给他提交个 Issue？

**Comment by Ryanjiena** [comment]
> 他在 Github 有个 [RunningCheese-Firefox](https://github.com/runningcheese/RunningCheese-Firefox/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) 的仓库，或许可以给他提交个 Issue？

昨天加了他博客上的那个微信，但是一直没有通过。 那个 github 账号看了一下也不是他常用的，估计不常登录😂

**Comment by Ryanjiena** [comment]
> 不能直接使用文章标题提取到的那个吗？

他那个下载链接是蓝奏云的呀

**Comment by Ryanjiena** [comment]
你把 runningcheese-chrome/edge 包下的 Data 目录里的内容拷贝到 chrome/edge-*-shuax 的 Data 目录下试一下，我这边 chrome 下测试了可以直接使用

**Comment by Ryanjiena** [comment]
记得先把你之前的 Data 目录备份下或者使用下面的方法：

1、登录你的 Google 帐号，书签、拓展就会自动同步了。
2、转移旧版配置的书签，将旧版配置文件夹下的 "\Data\Default\Bookmarks" 覆盖到新版同名文件。
3、如果书签图标是空白的，将旧版配置文件夹下的 "\Data\Default\Favicons" 覆盖到新版同名文件。
4、转移旧版配置的历史记录，将旧版配置文件夹下的 "\Data\Default\History" 覆盖到新版同名文件。
5、转移旧版配置的搜索引擎，将旧版配置文件夹下的 "\Data\Default\Web Data" 覆盖到新版同名文件。
6、更多说明参考这里：https://www.runningcheese.com/trouble-shooting

**Comment by wordpure** [comment]
> > 建议从官方发布文章的标题中提取。
> 
> 检测更新很简单，就像[这个](https://github.com/Ryanjiena/MetaVersion/issues/10) 。 但是有新版本号但是文件还是旧的，他网站没有提供下载直链，还需要我这边下载上传到 onedrive

> > >我本地这边处理起来有点麻烦(>﹏<)
> 
> > 不能直接使用文章标题提取到的那个吗？
> 
> 他那个下载链接是蓝奏云的呀

连在一起看的话，大佬的意思是奶酪发布的最新版用的都是同一个名称，不方便辨别文件是否更新，上传到 Onedrive 的时候也要额外处理？

**Comment by wordpure** [comment]
> 我这边 chrome 下测试了可以直接使用

> 记得先把你之前的 Data 目录备份下或者使用下面的方法：

非常感谢大佬的耐心解答和指导。

**Comment by wordpure** [comment]
其实我用的是自己配置的 Firefox 开发者版，下载 RunningCheese Firefox 只是想研究一下奶酪的配置。

当时不清楚情况，用 Scoop 安装前发现安装包的版本号比我在推文里看到的要低，就发了个 Issue😂

**Comment by JaimeZeng** [comment]
好吧..
