### ISSUE TITLE
Mactype-np 的版本降级

### ISSUE THREAD

**Issue by wordpure** [Ryanjiena/Meta#350]
![图片](https://user-images.githubusercontent.com/68013962/167460994-b6dd2179-858e-4891-a673-3f59ba7d88b4.png)

好像是作者将先前版本从 [Releases](https://github.com/snowie2000/mactype/releases/) 移动到  [Tags](https://github.com/snowie2000/mactype/tags/) 导致的。

![图片](https://user-images.githubusercontent.com/68013962/167461553-56e5b7f5-026e-417b-a7cb-f04464d5aa1c.png)

![图片](https://user-images.githubusercontent.com/68013962/167461581-ad6885f0-872f-4552-8a01-f05e771e7e83.png)

![图片](https://user-images.githubusercontent.com/68013962/167461592-9671c224-765f-4f68-a0a4-dd0614a4ae05.png)

**Comment by wordpure** [comment]
话说，Scoop 有没有可以避免这种反向升级的方法？

**Comment by Ryanjiena** [comment]
> 话说，Scoop 有没有可以避免这种反向升级的方法？

https://github.com/ScoopInstaller/Scoop/issues/4894#issuecomment-1115215855

**Comment by Ryanjiena** [comment]
> 好像是作者将先前版本从 [Releases](https://github.com/snowie2000/mactype/releases/) 移动到 [Tags]

我暂时会添加一个 mactype-beta-np 包，从 repo tags 检测更新。

**Comment by wordpure** [comment]
感谢🌹

**Comment by Ryanjiena** [comment]
> 感谢rose

🤣
