### ISSUE TITLE
[Request] Add wechat-zd423

### ISSUE THREAD

**Issue by IsaacWangTT** [Ryanjiena/Meta#352]
### Package Name

wechat-zd423

### Latest version

3.6.5.16

### Description

WeChat third-party modified version, maintained by 423down.com.

### Homepage

https://www.423down.com/8718.html

### Graphical interface

Yes

### Portable version

Yes

### Some indication of popularity/repute

希望添加微信的423down版本

### Download link(s)

```powershell
https://423down.lanzouo.com/b0f1ada0f
```

**Comment by Ryanjiena** [comment]
和 #347 一样，前几天 vps 到期了，这种包需要手动下载上传到 oneindex，暂时没精力去弄这个

**Comment by Ryanjiena** [comment]
暂时先用 [[wechat-portable.json]] 顶替下吧

**Comment by IsaacWangTT** [comment]
> 暂时先用 https://github.com/Ryanjiena/Meta/blob/master/bucket/wechat-portable.json 顶替下吧

好的好的
